version: "3.8"

networks:  
  tic-tac-toe-network:  
    name: tic-tac-toe-network  
    driver: bridge

services:
  backend:
      build:
        context: ./backend/demo
        dockerfile: Dockerfile
      networks:
        - tic-tac-toe-network
      ports:
        - "8080:8080"
      expose:
        - "8080"

  frontend:
    build:
      context: ./frontend/tic-tac-toe
      dockerfile: Dockerfile
    networks:
        - tic-tac-toe-network
    ports:
      - "3000:3000"
    expose:
      - "3000"
    depends_on:
      - backend